### ISSUE TITLE
difference between decoder_input_ids and lm_labels

### ISSUE THREAD

**Issue by mengyahuUSTC-PU** [patil-suraj/exploring-T5#2]
Hi, Suraj! Thanks for making this notebook.

I am new to this. I couldn't find the clear definition of 'lm_labels' on huggingface. I noticed in your notebook, you put the target ids into 'lm_labels' rather than decoder_input_ids. Could you let me know why? I am trying to use your code to fine tune on paraphrase generation. Thanks!

**Comment by patil-suraj** [comment]
hi @mengyahuUSTC-PU , The `T5ForConditionalGeneration` automatically creates `decoder_input_ids` from `lm_lables`  which is why I'm just passing `lm_labels`.

**Comment by mengyahuUSTC-PU** [comment]
@patil-suraj Thanks!! Yes, I found that in the source code. For people checking this thread in the future, this is the code:
if labels is not None and decoder_input_ids is None and decoder_inputs_embeds is None:  
decoder_input_ids = self._shift_right(labels)
